export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CART_TOGGLE_HIDDEN = 'CART_TOGGLE_HIDDEN';
export const ADD_CART_ITEMS = 'ADD_CART_ITEMS';
export const CLEAR_CART_ITEM = 'CLEAR_CART_ITEM';